package com.yourapp.carbot.bot;

public enum BotStep {
    NONE,
    WAITING_CAR_TYPE,
    WAITING_BRAND,
    WAITING_MAX_PRICE,
    WAITING_LOCATION,
    WAITING_MAX_MILEAGE,
    WAITING_TRANSMISSION,
    WAITING_FUEL_TYPE,
    WAITING_YEAR_FROM,
    EDITING_CAR_TYPE,
    EDITING_BRAND,
    EDITING_MAX_PRICE,
    EDITING_LOCATION,
    EDITING_MAX_MILEAGE,
    EDITING_TRANSMISSION,
    EDITING_FUEL_TYPE,
    EDITING_YEAR_FROM,
    WAITING_FEEDBACK,
    COMPLETED
}
