  server.port=${PORT:8080}
    
    spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    spring.datasource.username=${PGUSER}
    spring.datasource.password=${PGPASSWORD}
    
    spring.jpa.hibernate.ddl-auto=update

telegram:
  bot:
    token: 8637160094:AAEkzQnEwQDKMFP4evVZs9EBs9wis_ZB2Hs
    username: CarRadarCZ_bot
    admin-chat-ids: 1246486851